# -*- coding: utf-8 -*-
"""
Course content data for: Leadership Excellence for Working Professionals
14 modules. Each module dict feeds generate_course.py to produce 3 pages:
  1. Content page
  2. Reflection & Activity page
  3. Module Assessment page
"""

COURSE = {
    "course_id": "leadership-excellence-professionals",
    "course_title_en": "Leadership Excellence for Working Professionals",
    "course_title_ta": "பணிபுரியும் நிபுணர்களுக்கான தலைமைத்துவ சிறப்பு",
    "author": "N T Somasundaram",
    "author_title_en": "Certified Master Trainer | Career Consultant | Life Skills Educator",
    "whatsapp_number": "919843702244",
    "contact_email": "somasundaramnt.lifecoach@gmail.com",
}

MODULES = [
    {
        "num": 1,
        "title_en": "Foundations of Leadership",
        "title_ta": "தலைமைத்துவத்தின் அடிப்படைகள்",
        "objective_en": "Understand what leadership truly means, distinguish it from management, and identify your natural leadership style.",
        "objective_ta": "தலைமைத்துவம் என்றால் என்ன என்பதை புரிந்துகொள்ளுங்கள், அதை மேலாண்மையிலிருந்து வேறுபடுத்துங்கள், உங்கள் இயல்பான தலைமைத்துவ பாணியை அடையாளம் காணுங்கள்.",
        "concepts": [
            ("Leadership vs. Management", "Management is about coping with complexity — planning, budgeting, organizing, controlling. Leadership is about coping with change — setting direction, aligning people, motivating and inspiring. Working professionals often step into leadership without realizing the shift in mindset required: from 'doing the work' to 'enabling others to do the work.'"),
            ("The Four Foundational Leadership Styles", "1) Directive — clear instructions, useful in crises or with new team members. 2) Participative — invites input, builds buy-in, works well with experienced teams. 3) Delegative — hands over ownership, ideal for high-trust, high-skill teams. 4) Servant — leader supports the team's growth first; builds long-term loyalty. Most effective leaders flex between these based on the situation and the person."),
            ("Leadership is a Behaviour, Not a Title", "You do not need a designation to lead. Leadership shows up in how you take ownership of problems, how you support colleagues under pressure, and how you communicate under uncertainty. Positional authority can be given or taken away; earned influence cannot."),
            ("The Trust Equation", "People follow leaders they trust. Trust = Credibility + Reliability + Intimacy, divided by Self-Orientation. In practice: keep your commitments (reliability), be honest even when it's inconvenient (credibility), be approachable (intimacy), and focus on others' interests, not just your own advancement (low self-orientation)."),
        ],
        "reflection": [
            "Think of a leader who influenced you the most. What specific behaviours (not titles) made them effective?",
            "Which of the four leadership styles do you default to under pressure? Is that the style your current team actually needs?",
            "Where in your current role do you already show leadership, even without the formal title?",
            "What is one commitment you've made recently that you did not fully keep? What would rebuilding that trust look like?",
        ],
        "quiz": [
            ("Leadership is primarily about:", ["Controlling budgets and schedules", "Coping with change by setting direction and inspiring people", "Having a senior job title", "Avoiding conflict with the team"], 1),
            ("Which style is most appropriate for a brand-new, inexperienced team member facing an urgent deadline?", ["Delegative", "Servant", "Directive", "Participative"], 2),
            ("In the Trust Equation, a HIGH self-orientation tends to:", ["Increase trust", "Decrease trust", "Have no effect on trust", "Only matter for senior leaders"], 1),
            ("A person without a formal leadership title can still demonstrate leadership. True or False?", ["True", "False"], 0),
            ("Which of these best reflects a servant leadership mindset?", ["Focusing first on your own visibility to management", "Prioritizing your team's growth and removing obstacles for them", "Making all decisions without team input to move fast", "Avoiding feedback conversations to keep the peace"], 1),
        ],
    },
    {
        "num": 2,
        "title_en": "Self-Awareness & Emotional Intelligence for Leaders",
        "title_ta": "தலைவர்களுக்கான சுய விழிப்புணர்வு மற்றும் உணர்ச்சி நுண்ணறிவு",
        "objective_en": "Build the self-awareness and emotional regulation skills that separate reactive managers from composed leaders.",
        "objective_ta": "எதிர்வினையாற்றும் மேலாளர்களிடமிருந்து அமைதியான தலைவர்களை வேறுபடுத்தும் சுய விழிப்புணர்வு மற்றும் உணர்ச்சி கட்டுப்பாட்டு திறன்களை வளர்த்துக் கொள்ளுங்கள்.",
        "concepts": [
            ("The Four Domains of Emotional Intelligence", "Self-Awareness (recognizing your own emotions as they happen), Self-Management (regulating your reactions), Social Awareness (reading others' emotions and organizational dynamics), and Relationship Management (using this awareness to handle interactions and conflict well). Leadership failures are rarely about technical skill — they're usually EQ gaps."),
            ("The Pause Between Trigger and Response", "Between an event and your reaction, there is a small window. Leaders who pause — even for 3-5 seconds — before responding to criticism, bad news, or conflict make dramatically better decisions than those who react instantly. This pause can be trained through breathing techniques and simple self-questioning: 'What am I feeling right now, and is this the best response?'"),
            ("Reading the Room", "Social awareness means noticing tone, body language, and what's NOT being said in meetings. A team that goes quiet after a decision is announced is communicating something important, even without words. Leaders who only track task metrics and ignore emotional undercurrents lose their teams slowly and often don't see it coming."),
            ("Managing Your Own Stress as a Leadership Skill", "Your stress state is contagious — teams mirror their leader's anxiety or calm. Basic practices: naming the emotion ('I notice I'm frustrated'), separating urgency from importance, and taking short resets between high-stakes conversations, all measurably improve leadership decision quality."),
        ],
        "reflection": [
            "Describe a recent situation where you reacted quickly to something. Looking back, what might a 5-second pause have changed?",
            "On a scale of 1-10, how well do you currently read unspoken signals in your team or meetings? What's one thing you could start noticing this week?",
            "What is your most common stress trigger at work, and how does it typically show up in your behaviour toward others?",
            "Name one relationship at work that would benefit from more of your self-management this month.",
        ],
        "quiz": [
            ("Which is NOT one of the four EQ domains?", ["Self-Awareness", "Self-Management", "Technical Expertise", "Relationship Management"], 2),
            ("The 'pause' technique is most useful for:", ["Avoiding difficult conversations altogether", "Improving quality of response to triggering events", "Delaying all decisions indefinitely", "Reducing meeting length"], 1),
            ("A team going quiet after an announcement is an example of:", ["Social awareness data leaders should notice", "Something that should always be ignored", "A sign the meeting is over", "Irrelevant background noise"], 0),
            ("Leader stress states have little effect on team behaviour. True or False?", ["True", "False"], 1),
            ("Emotional Intelligence gaps are a common cause of:", ["Technical project failures only", "Leadership failures more often than skill gaps", "Only entry-level performance issues", "Nothing significant in leadership"], 1),
        ],
    },
    {
        "num": 3,
        "title_en": "Vision & Goal Setting",
        "title_ta": "தொலைநோக்கு மற்றும் இலக்கு அமைத்தல்",
        "objective_en": "Learn to craft a compelling vision and translate it into clear, achievable goals for your team.",
        "objective_ta": "கவர்ச்சிகரமான தொலைநோக்கை உருவாக்கவும், அதை உங்கள் குழுவிற்கான தெளிவான, அடையக்கூடிய இலக்குகளாக மாற்றவும் கற்றுக்கொள்ளுங்கள்.",
        "concepts": [
            ("Why Vision Matters", "A vision answers 'why does this work matter?' Teams with a clear sense of purpose outperform teams that only receive task lists, because purpose sustains motivation when tasks get repetitive or difficult. A good vision is short enough to remember and specific enough to guide decisions."),
            ("From Vision to Strategy to Goals", "Vision is the destination. Strategy is the broad route. Goals are the concrete milestones along that route. Leaders who skip straight to goals without connecting them to a larger 'why' often see compliance, not commitment."),
            ("SMART and Beyond: OKRs", "SMART goals (Specific, Measurable, Achievable, Relevant, Time-bound) remain useful for individual tasks. For team-level alignment, many organizations now use OKRs (Objectives and Key Results) — an ambitious Objective paired with 3-5 measurable Key Results that indicate progress."),
            ("Communicating Goals So They Stick", "Repetition is not nagging — it's reinforcement. Effective leaders repeat the 'why' behind goals in different formats: team meetings, 1:1s, written recaps. People need to hear the purpose multiple times, in multiple ways, before it truly sinks in and shapes behaviour."),
        ],
        "reflection": [
            "In one sentence, what is the 'why' behind the most important goal your team is working on right now?",
            "Pick one current team goal. Is it SMART? What's missing?",
            "How many times, and in how many formats, have you communicated your team's top priority this quarter?",
            "What is the difference between compliance and commitment in your team, and which one do you currently see more of?",
        ],
        "quiz": [
            ("A vision primarily answers:", ["How to complete a specific task", "Why the work matters", "What the budget is", "Who reports to whom"], 1),
            ("In the Vision-Strategy-Goals chain, goals represent:", ["The overall purpose", "The broad route", "Concrete milestones", "Company policy"], 2),
            ("SMART stands for Specific, Measurable, Achievable, Relevant, and:", ["Team-based", "Time-bound", "Technical", "Transparent"], 1),
            ("OKRs pair an ambitious Objective with:", ["A single deadline", "3-5 measurable Key Results", "A performance review", "A budget line"], 1),
            ("Repeating the 'why' behind a goal multiple times is best described as:", ["Unnecessary nagging", "Reinforcement that helps it stick", "A sign of poor planning", "Something to avoid"], 1),
        ],
    },
    {
        "num": 4,
        "title_en": "Effective Communication for Leaders",
        "title_ta": "தலைவர்களுக்கான திறமையான தொடர்பு",
        "objective_en": "Master clear, confident communication that builds trust and drives action.",
        "objective_ta": "நம்பிக்கையை உருவாக்கும் மற்றும் செயலைத் தூண்டும் தெளிவான, நம்பிக்கையான தொடர்பை கற்றுத் தேர்ச்சி பெறுங்கள்.",
        "concepts": [
            ("The Leader's Communication Responsibility", "As a leader, you are responsible not just for what you say, but for what is heard and understood. Ambiguity that seems harmless to you can create confusion, rework, or anxiety downstream. Precision is a form of respect for your team's time."),
            ("Active Listening as a Leadership Tool", "Listening to respond is different from listening to understand. Techniques: paraphrase what you heard before replying, ask one clarifying question before offering a solution, and resist the urge to interrupt with your own experience."),
            ("Giving Feedback That Lands", "Effective feedback is specific, timely, and behaviour-focused (not personality-focused). The SBI model helps: Situation (when/where), Behaviour (what you observed), Impact (the effect it had). This keeps feedback factual and reduces defensiveness."),
            ("Communicating Up, Down, and Across", "The message is the same but the framing changes: with senior leadership, lead with the bottom line and business impact; with your team, lead with context and the 'why'; with peers, lead with shared goals and collaboration, not competition."),
        ],
        "reflection": [
            "Recall a recent instance of miscommunication in your team. Where exactly did the ambiguity come from?",
            "Practice the SBI model: write out one piece of feedback you need to give, using Situation-Behaviour-Impact.",
            "How does your communication style change (or not change enough) when speaking to your manager versus your team?",
            "What is one habit (interrupting, jumping to solutions, multitasking while listening) you could reduce this week?",
        ],
        "quiz": [
            ("A leader's communication responsibility includes:", ["Only what they intended to say", "What is actually heard and understood by others", "Only formal written communication", "Nothing beyond meetings"], 1),
            ("SBI feedback stands for:", ["Skill, Behaviour, Improvement", "Situation, Behaviour, Impact", "Speed, Balance, Integrity", "Strategy, Business, Innovation"], 1),
            ("Listening to respond, rather than to understand, typically leads to:", ["Better solutions", "Missed context and weaker solutions", "Faster meetings with no downside", "Improved trust"], 1),
            ("When communicating with senior leadership, it's most effective to lead with:", ["A long background story", "The bottom line and business impact", "Personal opinions only", "Unrelated updates"], 1),
            ("Ambiguous instructions from a leader can lead to:", ["Increased efficiency", "Confusion and rework", "Nothing significant", "Faster team alignment"], 1),
        ],
    },
    {
        "num": 5,
        "title_en": "Decision-Making & Problem Solving",
        "title_ta": "முடிவெடுத்தல் மற்றும் பிரச்சனை தீர்த்தல்",
        "objective_en": "Apply structured frameworks to make sound decisions under pressure and ambiguity.",
        "objective_ta": "அழுத்தம் மற்றும் தெளிவின்மையின் கீழ் சரியான முடிவுகளை எடுக்க கட்டமைக்கப்பட்ட கட்டமைப்புகளைப் பயன்படுத்துங்கள்.",
        "concepts": [
            ("The Cost of Indecision", "Delayed decisions are still decisions — usually to let the default outcome happen. Leaders often overweight the risk of a wrong decision and underweight the cost of no decision at all. Naming this trade-off explicitly improves decision speed."),
            ("A Simple Decision Framework: Define, Gather, Weigh, Decide, Review", "1) Define the actual problem, not just the symptom. 2) Gather only the information that changes the decision. 3) Weigh 2-3 realistic options against your key criteria. 4) Decide and commit. 5) Review after implementation to learn, regardless of outcome."),
            ("Reversible vs. Irreversible Decisions", "Amazon's 'one-way door / two-way door' concept is useful: most decisions are two-way doors (reversible) and should be made quickly by individuals or small groups. Reserve slow, consensus-heavy processes for true one-way doors (irreversible, high-stakes)."),
            ("Root Cause Thinking", "Use the '5 Whys' to move past surface symptoms: ask 'why' repeatedly until you reach a cause you can actually act on. This prevents solving the same recurring problem repeatedly without addressing its source."),
        ],
        "reflection": [
            "Think of a decision you've been delaying. What is the actual cost of continuing not to decide?",
            "Classify your last three big decisions as reversible or irreversible. Did you spend the right amount of time on each, relative to that classification?",
            "Pick a recurring problem in your team and run the '5 Whys' on it. What root cause did you reach?",
            "What criteria do you typically weigh most heavily when deciding — and are they still the right ones?",
        ],
        "quiz": [
            ("Delaying a decision is best understood as:", ["A neutral action with no consequence", "A decision to let the default outcome happen", "Always the safest choice", "Irrelevant to leadership"], 1),
            ("In the Define-Gather-Weigh-Decide-Review framework, 'Gather' means:", ["Collecting all possible information regardless of relevance", "Collecting only information that changes the decision", "Skipping data collection entirely", "Asking only senior leaders"], 1),
            ("A 'two-way door' decision is:", ["Irreversible and high-stakes", "Reversible and should be made quickly", "Always made by committee", "Only relevant to hiring"], 1),
            ("The '5 Whys' technique is used to:", ["Delay a decision", "Identify a root cause", "Avoid taking responsibility", "Replace all data analysis"], 1),
            ("Leaders often make the mistake of:", ["Underweighting the cost of indecision", "Overweighting the cost of indecision", "Never considering risk", "Ignoring all frameworks equally"], 0),
        ],
    },
    {
        "num": 6,
        "title_en": "Delegation & Empowerment",
        "title_ta": "பொறுப்பு ஒப்படைத்தல் மற்றும் அதிகாரமளித்தல்",
        "objective_en": "Delegate effectively to grow your team's capability while freeing your own capacity for higher-value work.",
        "objective_ta": "உங்கள் குழுவின் திறனை வளர்க்கவும், உயர்-மதிப்பு வேலைக்கு உங்கள் சொந்த திறனை விடுவிக்கவும் திறம்பட பொறுப்பு ஒப்படைக்கவும்.",
        "concepts": [
            ("Why Leaders Under-Delegate", "Common reasons: 'It's faster if I do it myself,' fear of losing control, or belief that delegation looks like abdicating responsibility. Each of these caps a leader's growth and the team's growth simultaneously."),
            ("Delegating the Outcome, Not Just the Task", "Effective delegation transfers ownership of an outcome, with agreed boundaries, not a rigid step-by-step script. This is what develops judgment in your team members rather than just following instructions."),
            ("The Delegation Levels Model", "Level 1: Do exactly as I say. Level 2: Research and report back options, I'll decide. Level 3: Decide and inform me before acting. Level 4: Decide and act, update me periodically. Level 5: Full autonomy. Matching the right level to the person's skill and the task's risk is the core delegation skill."),
            ("Delegation Requires Follow-Through, Not Micromanagement", "Set clear checkpoints in advance (not surprise check-ins), define what 'done well' looks like, and resist the urge to redo the work yourself when it's not exactly how you would have done it — unless it fails to meet the agreed standard."),
        ],
        "reflection": [
            "What is one task you are currently holding onto that could be delegated? What's stopping you?",
            "For that task, which Delegation Level (1-5) would be appropriate for the team member you have in mind?",
            "Describe a time you delegated something and then took it back. What triggered that, and was it justified?",
            "What would 'done well' look like for a task you plan to delegate this month? Have you actually communicated that clearly?",
        ],
        "quiz": [
            ("A common reason leaders under-delegate is:", ["Too much free time", "Belief that it's faster to do it themselves", "Excess trust in the team", "Lack of tasks to assign"], 1),
            ("Effective delegation transfers:", ["A rigid step-by-step script only", "Ownership of an outcome with agreed boundaries", "No responsibility at all", "Only low-value busywork"], 1),
            ("In the Delegation Levels model, Level 5 means:", ["Do exactly as instructed", "Full autonomy", "Report back options only", "Decide and inform before acting"], 1),
            ("Matching delegation level to the task and person is based on:", ["Random assignment", "The person's skill and the task's risk", "Seniority alone", "Personal friendship"], 1),
            ("Micromanaging after delegating typically:", ["Builds trust and confidence", "Undermines the growth delegation was meant to create", "Has no effect on the relationship", "Speeds up long-term development"], 1),
        ],
    },
    {
        "num": 7,
        "title_en": "Building & Leading High-Performance Teams",
        "title_ta": "உயர் செயல்திறன் கொண்ட குழுக்களை உருவாக்குதல் மற்றும் வழிநடத்துதல்",
        "objective_en": "Understand team dynamics and apply practical techniques to build cohesion and performance.",
        "objective_ta": "குழு இயக்கவியலைப் புரிந்துகொண்டு, ஒற்றுமை மற்றும் செயல்திறனை உருவாக்க நடைமுறை நுட்பங்களைப் பயன்படுத்துங்கள்.",
        "concepts": [
            ("Tuckman's Stages of Team Development", "Forming (polite, cautious) → Storming (conflict and testing boundaries) → Norming (agreements form) → Performing (high trust, high output) → Adjourning (wrap-up). Storming is uncomfortable but necessary — teams that avoid it never truly reach Performing."),
            ("Psychological Safety as the Foundation", "Google's Project Aristotle research found psychological safety — the shared belief that it's safe to take interpersonal risks — was the single biggest predictor of team effectiveness, more than individual talent. Leaders build this by responding to mistakes and dissent with curiosity, not punishment."),
            ("Clarity of Roles Reduces Friction", "Ambiguous role boundaries are a leading cause of team conflict, often mistaken for personality clashes. A simple RACI exercise (who is Responsible, Accountable, Consulted, Informed) for key processes resolves much of this friction quickly."),
            ("Celebrating Progress, Not Just Outcomes", "High-performing teams get recognition for effort and improvement along the way, not only for final results. This sustains motivation on long projects and reduces burnout during periods where outcomes aren't yet visible."),
        ],
        "reflection": [
            "Which Tuckman stage is your team currently in? What evidence tells you that?",
            "On a scale of 1-10, how psychologically safe do you think your team feels raising concerns with you? How do you know?",
            "Is there a recurring 'personality clash' on your team that might actually be a role clarity issue?",
            "What is one piece of progress (not just an outcome) you could recognize in your team this week?",
        ],
        "quiz": [
            ("The stage of team development involving conflict and testing boundaries is:", ["Forming", "Storming", "Norming", "Performing"], 1),
            ("According to Project Aristotle, the biggest predictor of team effectiveness was:", ["Individual talent", "Psychological safety", "Office location", "Team size"], 1),
            ("RACI is a tool used to clarify:", ["Salary bands", "Roles and responsibilities", "Vacation schedules", "Marketing strategy"], 1),
            ("Recognizing only final outcomes, not progress, tends to:", ["Sustain motivation on long projects", "Increase burnout risk during long projects", "Have no effect on morale", "Improve psychological safety automatically"], 1),
            ("Avoiding the Storming stage entirely usually means a team:", ["Reaches Performing faster", "Never truly develops into a high-performing team", "Has excellent psychological safety", "Skips Forming as well"], 1),
        ],
    },
    {
        "num": 8,
        "title_en": "Conflict Resolution & Difficult Conversations",
        "title_ta": "மோதல் தீர்வு மற்றும் கடினமான உரையாடல்கள்",
        "objective_en": "Handle disagreement and difficult conversations constructively, without avoidance or escalation.",
        "objective_ta": "தவிர்க்காமல் அல்லது அதிகரிக்காமல் கருத்து வேறுபாடு மற்றும் கடினமான உரையாடல்களை ஆக்கபூர்வமாக கையாளுங்கள்.",
        "concepts": [
            ("Why Leaders Avoid Difficult Conversations", "Fear of damaging the relationship, fear of an emotional reaction, or simply not knowing how to start. But avoided conflict doesn't disappear — it resurfaces as passive resistance, gossip, or disengagement, usually worse than the original issue."),
            ("Separating Position from Interest", "In most conflicts, people state a position ('I want X') that hides an underlying interest ('I need to feel respected' or 'I need predictability'). Asking 'what matters to you about this?' surfaces the real issue faster than debating positions."),
            ("A Structure for Difficult Conversations", "1) State your intention (\"I want to work through this together\"). 2) Describe the specific behaviour and impact, not character. 3) Invite their perspective and actually listen. 4) Co-create a way forward. 5) Agree on a follow-up point."),
            ("Managing Your Own Defensiveness", "When receiving pushback, resist the urge to immediately justify or counter-argue. A brief acknowledgment ('I hear that this landed badly, tell me more') before responding keeps the conversation productive rather than combative."),
        ],
        "reflection": [
            "Is there a conversation you've been avoiding at work? What specifically are you afraid will happen if you have it?",
            "Think of a recent conflict. What was the stated position, and what might the underlying interest have been?",
            "Using the 5-step structure, draft an opening line for a difficult conversation you need to have.",
            "Recall a time you became defensive when receiving feedback. What would an 'acknowledge first' response have sounded like?",
        ],
        "quiz": [
            ("Avoided conflict typically:", ["Disappears on its own", "Resurfaces as passive resistance or disengagement", "Always resolves faster", "Improves team trust automatically"], 1),
            ("The underlying 'interest' behind a stated position is:", ["Always identical to the position", "What actually matters to the person, often unstated", "Irrelevant to resolving conflict", "Only relevant in negotiations, not conflict"], 1),
            ("In the 5-step difficult conversation structure, step 1 is:", ["Assign blame", "State your intention", "Threaten consequences", "End the meeting"], 1),
            ("Describing 'specific behaviour and impact, not character' helps:", ["Escalate the conflict", "Keep feedback factual and reduce defensiveness", "Make the conversation more personal", "Avoid the real issue"], 1),
            ("Acknowledging pushback before responding tends to:", ["Make you look weak", "Keep the conversation productive rather than combative", "Have no effect on the outcome", "Always be unnecessary"], 1),
        ],
    },
    {
        "num": 9,
        "title_en": "Coaching & Mentoring Skills",
        "title_ta": "பயிற்சி மற்றும் வழிகாட்டுதல் திறன்கள்",
        "objective_en": "Develop coaching conversations that help team members solve their own problems and grow.",
        "objective_ta": "குழு உறுப்பினர்கள் தங்கள் சொந்த பிரச்சனைகளை தீர்க்கவும் வளரவும் உதவும் பயிற்சி உரையாடல்களை உருவாக்குங்கள்.",
        "concepts": [
            ("Coaching vs. Advising vs. Directing", "Directing tells someone what to do. Advising offers your own solution as an option. Coaching asks questions that help the person find their own solution. Coaching builds longer-lasting capability, though it takes more patience upfront."),
            ("The GROW Model", "Goal (what do you want to achieve?), Reality (what's the current situation?), Options (what could you try?), Will/Way Forward (what will you actually do, and by when?). This simple structure turns a vague conversation into a concrete commitment."),
            ("Powerful Questions Over Quick Answers", "Resist the instinct to solve the problem for your team member. Ask: 'What have you already tried?', 'What would you do if you were fully confident?', 'What's the real obstacle here?' These questions build problem-solving muscle rather than dependency on you."),
            ("Mentoring for Long-Term Growth", "Mentoring differs from coaching by drawing on your own experience and relationships to guide someone's broader career development, not just a single problem. Good mentors ask about long-term goals, not only immediate performance."),
        ],
        "reflection": [
            "Recall the last time a team member brought you a problem. Did you coach, advise, or direct? Was that the right choice for the situation?",
            "Pick a current challenge someone on your team is facing and draft 2-3 GROW-model questions you could ask them.",
            "What is one instance where you solved a problem for someone that they could have solved themselves with the right question?",
            "Who on your team would benefit most from a mentoring relationship with you, and what would you focus on first?",
        ],
        "quiz": [
            ("Coaching, compared to directing, primarily involves:", ["Giving explicit instructions", "Asking questions to help someone find their own solution", "Ignoring the problem", "Taking over the task"], 1),
            ("In the GROW model, 'R' stands for:", ["Results", "Reality", "Resources", "Recognition"], 1),
            ("Asking 'what have you already tried?' is an example of:", ["Directing", "A powerful coaching question", "Avoiding the issue", "Micromanaging"], 1),
            ("Mentoring differs from coaching mainly by:", ["Focusing only on a single immediate task", "Drawing on the mentor's experience to guide broader career growth", "Never involving conversation", "Being identical to directing"], 1),
            ("Solving problems for your team members every time tends to:", ["Build their independent problem-solving skill", "Build dependency rather than capability", "Have no long-term effect", "Always save time overall"], 1),
        ],
    },
    {
        "num": 10,
        "title_en": "Change Management & Leading Through Uncertainty",
        "title_ta": "மாற்ற மேலாண்மை மற்றும் நிச்சயமற்ற தன்மையின் மூலம் வழிநடத்துதல்",
        "objective_en": "Lead your team through organizational change and uncertainty with clarity and resilience.",
        "objective_ta": "தெளிவு மற்றும் நெகிழ்ச்சியுடன் நிறுவன மாற்றம் மற்றும் நிச்சயமற்ற தன்மையின் மூலம் உங்கள் குழுவை வழிநடத்துங்கள்.",
        "concepts": [
            ("Why People Resist Change", "Resistance is rarely about the change itself — it's usually about loss of control, unclear impact on the individual, or past experiences with poorly managed change. Naming these underlying fears is more effective than simply repeating the business case for change."),
            ("Kotter's 8-Step Model (Simplified for Team Leaders)", "Create urgency, build a coalition of support, form a clear vision, communicate it repeatedly, remove obstacles, generate short-term wins, keep pushing, and anchor the new way of working into team norms. Most change efforts fail from skipping short-term wins and declaring victory too early."),
            ("The Leader's Role During Ambiguity", "When the full picture isn't yet clear, leaders should be transparent about what is and isn't known, avoid false certainty, and focus the team on what can be controlled in the immediate term, rather than speculating endlessly about the unknown."),
            ("Building Team Resilience", "Resilient teams are built before the crisis, not during it — through trust, clear communication habits, and psychological safety established in calmer times. Leaders who only invest in relationships during a crisis usually find the well is dry."),
        ],
        "reflection": [
            "Think about a recent change in your organization. What underlying fear (not stated objection) might explain resistance to it?",
            "Using Kotter's model, which step is most often missing when change initiatives fail in your organization?",
            "Describe a time you had to lead with incomplete information. What did you say, and would you say it differently now?",
            "What is one small habit you could build now, in calm times, that would strengthen your team's resilience for future change?",
        ],
        "quiz": [
            ("Resistance to change is usually rooted in:", ["Laziness", "Loss of control and unclear personal impact", "A dislike of leadership in general", "Lack of intelligence"], 1),
            ("A common reason change efforts fail, per Kotter, is:", ["Too many short-term wins", "Declaring victory too early and skipping short-term wins", "Too much communication", "Excess urgency"], 1),
            ("During ambiguity, leaders should:", ["Project false certainty to reassure the team", "Be transparent about what is and isn't known", "Avoid discussing the situation at all", "Wait silently until full clarity emerges"], 1),
            ("Team resilience is best built:", ["Only during an active crisis", "Before the crisis, through trust and communication habits", "By avoiding difficult topics entirely", "Through strict top-down control alone"], 1),
            ("Kotter's model begins with:", ["Anchoring new norms", "Creating urgency", "Generating short-term wins", "Removing obstacles"], 1),
        ],
    },
    {
        "num": 11,
        "title_en": "Time & Priority Management for Leaders",
        "title_ta": "தலைவர்களுக்கான நேரம் மற்றும் முன்னுரிமை மேலாண்மை",
        "objective_en": "Manage your time and priorities as a leader, distinguishing urgent work from truly important leadership activities.",
        "objective_ta": "அவசர வேலைகளை உண்மையான முக்கிய தலைமைத்துவ செயல்பாடுகளிலிருந்து வேறுபடுத்தி, ஒரு தலைவராக உங்கள் நேரம் மற்றும் முன்னுரிமைகளை நிர்வகிக்கவும்.",
        "concepts": [
            ("The Eisenhower Matrix for Leaders", "Urgent & Important (do now), Important not Urgent (schedule — this is where real leadership work lives: coaching, planning, relationship-building), Urgent not Important (delegate), Neither (eliminate). Most leaders spend too much time in 'Urgent' and starve the 'Important not Urgent' quadrant."),
            ("Protecting Time for Leadership Work", "Coaching conversations, strategic thinking, and relationship-building rarely feel urgent on any given day, so they get pushed indefinitely unless deliberately scheduled. Leaders who block calendar time for this see measurably stronger team outcomes over a quarter."),
            ("The Cost of Constant Availability", "Being interruptible at all times fragments deep thinking and signals to the team that reactive fire-fighting is the norm. Setting reasonable response-time expectations (not silence, but not instant either) models healthier work patterns for the whole team."),
            ("Saying No as a Leadership Skill", "Every 'yes' to a low-priority request is a 'no' to something more important, whether you say it explicitly or not. Leaders who can decline (or negotiate scope/timeline) respectfully protect both their own capacity and their team's focus."),
        ],
        "reflection": [
            "Map your last week's actual time (roughly) onto the Eisenhower Matrix. Which quadrant took the most time, and does that match your priorities?",
            "What is one 'Important not Urgent' leadership activity you've been neglecting? When will you schedule it this week?",
            "How available do you make yourself for interruptions, and is that serving your team or training them to always escalate?",
            "Recall a recent 'yes' you gave to a low-priority request. What did it cost you elsewhere?",
        ],
        "quiz": [
            ("Where does most real leadership work (coaching, planning) tend to sit in the Eisenhower Matrix?", ["Urgent & Important", "Important, not Urgent", "Urgent, not Important", "Neither urgent nor important"], 1),
            ("Leadership activities that aren't urgent tend to:", ["Get done first automatically", "Get pushed indefinitely unless deliberately scheduled", "Never matter for team outcomes", "Require no calendar planning"], 1),
            ("Constant availability for interruptions tends to:", ["Improve deep thinking", "Fragment deep thinking and normalize reactive work", "Have no impact on team norms", "Reduce fire-fighting"], 1),
            ("Saying yes to a low-priority request is:", ["Free, with no trade-off", "Implicitly a 'no' to something more important", "Always the safest leadership choice", "Irrelevant to time management"], 1),
            ("The Eisenhower Matrix's four quadrants are based on:", ["Seniority and budget", "Urgency and importance", "Team size and location", "Personal preference only"], 1),
        ],
    },
    {
        "num": 12,
        "title_en": "Influence, Negotiation & Stakeholder Management",
        "title_ta": "செல்வாக்கு, பேச்சுவார்த்தை மற்றும் பங்குதாரர் மேலாண்மை",
        "objective_en": "Build influence without formal authority and negotiate win-win outcomes with stakeholders.",
        "objective_ta": "முறையான அதிகாரம் இல்லாமல் செல்வாக்கை உருவாக்கி, பங்குதாரர்களுடன் இரு தரப்புக்கும் வெற்றி தரும் முடிவுகளை பேச்சுவார்த்தை நடத்துங்கள்.",
        "concepts": [
            ("Influence Without Authority", "Much of a leader's real work happens with peers, other departments, and senior stakeholders where you have no direct authority. Influence here comes from credibility (track record), reciprocity (having helped others before), and clearly connecting your ask to the other person's own goals."),
            ("Cialdini's Principles of Influence (Applied at Work)", "Reciprocity (give first), Consistency (get small commitments before big ones), Social Proof (show others have adopted this), Authority (cite relevant expertise, not just seniority), Liking (genuine rapport), Scarcity (real, not manufactured, urgency). Used ethically, these are simply good relationship-building, not manipulation."),
            ("Principled Negotiation", "Separate the people from the problem. Focus on underlying interests, not stated positions. Generate multiple options before deciding. Use objective criteria (data, market rates, precedent) to resolve disagreements rather than pure willpower or seniority."),
            ("Mapping Your Stakeholders", "For any significant initiative, identify stakeholders by their level of influence and level of interest. High-influence, high-interest stakeholders need close, frequent engagement; high-influence, low-interest stakeholders need periodic, concise updates so they stay supportive without feeling burdened."),
        ],
        "reflection": [
            "Think of a stakeholder you need more influence with, but have no formal authority over. What's one thing you could do for them before you need something in return?",
            "Pick a recent negotiation (formal or informal). Did you focus on positions or underlying interests? What might change if you focused on interests?",
            "Draft a simple stakeholder map for a current project: who is high-influence/high-interest, and how are you engaging them?",
            "Which of Cialdini's principles do you use least, and where could you apply it ethically this month?",
        ],
        "quiz": [
            ("Influence without formal authority is best built through:", ["Demanding compliance", "Credibility, reciprocity, and connecting to others' goals", "Avoiding all interaction with peers", "Formal job titles"], 1),
            ("Principled negotiation focuses on:", ["Winning at all costs", "Underlying interests, not just stated positions", "Ignoring the other party's concerns", "Seniority alone"], 1),
            ("High-influence, high-interest stakeholders generally need:", ["No engagement at all", "Close, frequent engagement", "Only annual updates", "To be avoided"], 1),
            ("Reciprocity, as a principle of influence, means:", ["Demanding something first", "Giving or helping first, before asking for something", "Ignoring past favors", "Only applicable to sales"], 1),
            ("Objective criteria in negotiation (e.g. market data) help to:", ["Increase personal conflict", "Resolve disagreements without relying on pure willpower or seniority", "Make negotiations less fair", "Replace all relationship-building"], 1),
        ],
    },
    {
        "num": 13,
        "title_en": "Ethical Leadership & Integrity",
        "title_ta": "நெறிமுறை தலைமைத்துவம் மற்றும் நேர்மை",
        "objective_en": "Lead with integrity, make ethically sound decisions, and build a culture of trust.",
        "objective_ta": "நேர்மையுடன் வழிநடத்தி, நெறிமுறையான முடிவுகளை எடுத்து, நம்பிக்கை கலாச்சாரத்தை உருவாக்குங்கள்.",
        "concepts": [
            ("Why Ethics is a Leadership Skill, Not Just a Personal Virtue", "A leader's ethical choices are amplified — your team watches what you do far more than what you say, and they calibrate their own standards accordingly. Small compromises ('just this once') are rarely isolated; they set a precedent the team notices."),
            ("A Simple Ethical Decision Test", "Before a decision: 1) Is it legal? 2) Does it align with our stated values? 3) Would I be comfortable if this decision were made public? 4) How would I feel if someone did this to me or my team? If any answer gives pause, slow down before proceeding."),
            ("Handling Ethical Grey Areas", "Not every dilemma has a clean answer. When principles conflict (e.g., loyalty to a struggling team member vs. fairness to the whole team), name the tension explicitly rather than pretending there's an easy answer, and involve trusted advisors or HR where appropriate."),
            ("Building a Speak-Up Culture", "People only report concerns, mistakes, or ethical grey areas if they trust the response won't be punitive. Leaders build this by responding to bad news calmly, thanking people for raising issues (even inconvenient ones), and visibly following through on what they said they'd do about it."),
        ],
        "reflection": [
            "Recall a recent small compromise you or your team made ('just this once'). What precedent might it have set?",
            "Run a recent difficult decision through the four-question ethical test. Does it hold up?",
            "Describe an ethical grey area you're currently navigating. What competing principles are in tension?",
            "How confident are you that your team would bring you bad news quickly? What evidence supports that confidence, or challenges it?",
        ],
        "quiz": [
            ("A leader's ethical choices are:", ["Private and have no impact on the team", "Amplified, since the team watches and calibrates accordingly", "Only relevant at senior executive levels", "Irrelevant to team culture"], 1),
            ("Small ethical compromises ('just this once') tend to:", ["Stay isolated with no further effect", "Set a precedent the team notices", "Always go unnoticed", "Improve team trust"], 1),
            ("A speak-up culture depends most on:", ["Strict punishment for any mistake", "Trust that raising concerns won't be punished", "Avoiding all difficult conversations", "Formal policy documents alone"], 1),
            ("When ethical principles conflict with no clean answer, leaders should:", ["Pretend there's an easy answer", "Name the tension explicitly and seek appropriate input", "Ignore the dilemma", "Always choose loyalty over fairness by default"], 1),
            ("One question in the simple ethical decision test is:", ["Would I be comfortable if this became public?", "Will this increase quarterly profit?", "Is this the fastest option?", "Will this impress senior management?"], 0),
        ],
    },
    {
        "num": 14,
        "title_en": "Personal Leadership Action Plan & Continuous Growth",
        "title_ta": "தனிப்பட்ட தலைமைத்துவ செயல் திட்டம் மற்றும் தொடர்ச்சியான வளர்ச்சி",
        "objective_en": "Consolidate your learning into a concrete, personal leadership development plan.",
        "objective_ta": "உங்கள் கற்றலை ஒரு உறுதியான, தனிப்பட்ட தலைமைத்துவ மேம்பாட்டு திட்டமாக ஒருங்கிணைக்கவும்.",
        "concepts": [
            ("Why Most Development Plans Fail", "Vague intentions ('be a better communicator') rarely change behaviour. Specific, observable, time-bound commitments ('in team meetings this month, I will pause 3 seconds before responding to disagreement') are far more likely to stick, because they're easy to notice and self-check."),
            ("The 70-20-10 Model for Leadership Growth", "Roughly 70% of leadership growth happens through on-the-job experience and stretch assignments, 20% through feedback and relationships (mentors, peers), and 10% through formal training like this course. This course is most valuable when paired with real application in your role."),
            ("Choosing Your Top 2-3 Priorities", "Trying to change everything from all 14 modules at once leads to changing nothing. Reviewing your reflections from each module, identify the 2-3 leadership behaviours that would have the highest impact on your team if improved in the next 90 days."),
            ("Building an Accountability Loop", "Growth sticks when there's a feedback loop: share your development priorities with your manager or a peer, set a specific check-in date, and ask a trusted colleague to give you honest signal on whether they've noticed the change."),
        ],
        "reflection": [
            "Looking back across all 14 modules, which 2-3 leadership behaviours would have the biggest impact if you improved them in the next 90 days?",
            "For your top priority, write one specific, observable, time-bound commitment (not a vague intention).",
            "Who will you share this development plan with, and when will your first check-in be?",
            "What is one piece of on-the-job experience (a stretch assignment, a difficult conversation, a new responsibility) you could seek out in the next month to accelerate this growth?",
        ],
        "quiz": [
            ("Development plans are more likely to stick when they are:", ["Vague and broad", "Specific, observable, and time-bound", "Focused on all areas simultaneously", "Kept entirely private"], 1),
            ("In the 70-20-10 model, the largest share of leadership growth comes from:", ["Formal training", "On-the-job experience and stretch assignments", "Reading books alone", "Watching videos"], 1),
            ("Trying to improve on all 14 modules at once typically results in:", ["Faster, more complete growth", "Changing very little in practice", "No downside at all", "Guaranteed success"], 1),
            ("An accountability loop typically includes:", ["Keeping goals completely private", "Sharing priorities and setting a specific check-in date", "Avoiding feedback from colleagues", "Ignoring manager input"], 1),
            ("This course is most valuable when:", ["Taken in isolation with no on-the-job application", "Paired with real application in your role", "Immediately forgotten after completion", "Replacing all workplace experience"], 1),
        ],
    },
]
